logging.level.org.zalando.logbook: TRACE

server:
  port: 8080

spring:
  main:
    log-startup-info: true # выводим служебную информацию
    # banner-mode: off       # не выводим баннер
  h2:
    console:
      enabled: true
#      #path: /h2-console
#      settings.trace: false
#      settings.web-allow-others: true
  sql.init.mode: ALWAYS
  datasource:
    #url: jdbc:h2:mem:mydb
    url: jdbc:h2:file:./db/filmorate
#    DB_CLOSE_DELAY: -1
    DB_CLOSE_ON_EXIT: FALSE
#    AUTO_RECONNECT: TRUE
#    MODE: PostgreSQL
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    #show-sql: true

java-filmorate:
  storage:
    film: filmDbRepository # inMemoryFilmStorage
    user: userDbRepository